version: '3.8'

services:
  api:
    container_name: fastapi
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: api/
      dockerfile: Dockerfile
    volumes:
      - ./shared:/usr/src/app/shared
    ports:
      - "5000:5000"
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        python api.py
        alembic upgrade head
        
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mosquitto_data:
  postgres_data: